---
# handlers file for deploy_vsftpd

- name: restart firewalld
  service: name=firewalld state=restarted

- name: firewalld reload
  command: firewall-cmd --reload

- name: sec_cont
  shell:
    cmd: chcon -t public_content_rw_t "{{ upload_folder }}"