---
- name: Install Apache, create index.html, open tcp 80/443
#  hosts: [webservers]
  hosts: node02.lab.local
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  roles:
#    - { role: deploy_apache, when: ansible_system == 'Linux' }
     - { role: deploy_vsftpd, when: ansible_system == 'Linux' }

