---
- hosts: [webservers]
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
      - my_vault.yml
  tasks:
    - name: Create Users
      user:
        name: "{{ item.name }}"
        password: "{{ item.pass }}"
#        password: "{{ password | password_hash('sha512') }}"
        comment: "{{ item.name }}@lab.local"
        shell: /bin/bash
#        update_password: on_create
      loop:
        - { name: 'Alice', pass: "{{ Alice_pass | password_hash('sha512') }}" }
        - { name: 'Bob', pass: "{{ Bob_pass | password_hash('sha512') }}" }
        - { name: 'Carol', pass: "{{ Carol_pass | password_hash('sha512') }}" }


#      loop: [Alice, Bob, Carol]
#        - Alice
#        - Bob
#        - Carol