---
- name: install a package
  hosts: node01.lab.local
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: install httpd
      package: name=httpd
      state: latest
...