---
- hosts: node01.lab.local
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Install httpd
      yum: pkg=httpd state=latest
    - name: Enable httpd on system reboot
      service: name=httpd enabled=yes
      notify: restart httpd
    - name: Creating an index.html
        copy:
          dest: "/var/www/html/"
          content: "Welcome to my web server"
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
...