---
- hosts: [webservers]
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Install httpd
      yum: pkg=httpd state=latest
    - name: Enable httpd on system reboot
      service: name=httpd enabled=yes
      notify: restart httpd
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
...