---
- hosts: [webservers]
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Install httpd
      yum: pkg=httpd state=latest
    - name: Enable httpd on system reboot
      service: name=httpd enabled=yes
      notify: restart httpd
    - name: Creating an index.html
      copy:
        dest: "/var/www/html/index.html"
        content: |
          Welcome to my web server
    - name: Enable FirewallD on system reboot
      service: name=firewalld enabled=yes
      notify: restart firewalld
    - name: FirewallD enable port 80
      firewalld:
        zone: public
        port: 80/tcp
        permanent: true
        state: enabled
      notify: firewalld reload
    - name: FirewallD enable port 443
        firewalld:
          zone: public
          port: 443/tcp
          permanent: true
          state: enabled
        notify: firewalld reload
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
    - name: restart firewalld
      service: name=firewalld state=restarted
    - name: firewalld reload
      command: firewall-cmd --reload
...