---
- hosts: node01.lab.local
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: add first change
      lineinfile:
        path: /etc/default/grub
        backrefs: yes
        regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames)\"[^\"]+)(\".*)'
        line: '\1 net.ifnames=0\2'

    - name: add second change
      lineinfile:
        path: /etc/default/grub
        backrefs: yes
        regexp: '^(GRUB_CMDLINE_LINUX=(?!.* biosdevname)\"[^\"]+)(\".*)'
        line: '\1 biosdevname=0\2'
...