---
- hosts: [webservers]
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Uninstall httpd
      yum: pkg=httpd state=removed
    - name: Delete index.html
      file:
        path: "/var/www/html/index.html"
        state: absent
    - name: FirewallD disable http/https
      firewalld:
        zone: public
        port: "{{ item }}"
        permanent: true
        state: disabled
      loop:
        - 80/tcp
        - 443/tcp
      notify: firewalld reload
  handlers:
    - name: firewalld reload
      command: firewall-cmd --reload
...