---
- hosts: [webservers]
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Uninstall httpd
      yum: pkg=httpd state=removed
#    - name: Enable httpd on system reboot
#      service: name=httpd enabled=yes
#      notify: restart httpd
#    - name: Creating an index.html
#      copy:
#        dest: "/var/www/html/index.html"
#        content: |
#          Welcome to my web server
    - name: Enable FirewallD on system reboot
      service: name=firewalld enabled=yes
      notify: restart firewalld
    - name: FirewallD enable http/https
      firewalld:
        zone: public
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - 80/tcp
        - 443/tcp
      notify: firewalld reload
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
    - name: restart firewalld
      service: name=firewalld state=restarted
    - name: firewalld reload
      command: firewall-cmd --reload
...