---
- hosts: node01.lab.local
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
#    - name: add net.ifnames
#      replace:
#        path: /etc/default/grub
#        regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$'
#        replace: '\1 {{ option }}={{ value }}\2'
#      vars:
#        option: net.ifnames
#        value: 0











    - name: add biosdevname
#      replace:
#          path: /etc/default/grub
#          regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$'
#          replace: '\1 {{ option }}={{ value }}\2'
#      vars:
#        option: biosdevname
#        value: 0
      lineinfile:
        path: /etc/default/grub
        backrefs: yes
#        regexp: '^(GRUB_CMDLINE_LINUX=(?!.* audit)\"[^\"]+)(\".*)'
        regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$'
        line: "{{ item }}"
      loop:
#        - \1 audit=1\2
        - net.ifnames=0
        - biosdevname=0



#        search_string: 'net.ifnames=0'
#        regexp: '^(net.ifnames=0)'
#        insertbefore: '^(elevator=noop)'
#        line: 'test line'
#        regexp: "{{ item }}"
#        state: absent
#        insertafter: '1234'
#        line: 'net.ifnames=0'
#        backrefs: yes
#      loop:
#        - ^GRUB_CMDLINE_LINUX="
##        - 443/tcp
##        insertafter: '^0'
##        line: test
##  handlers:
##    - name: firewalld reload
##      command: firewall-cmd --reload
...