---
# tasks file for deploy_apache

- name: Install httpd
  yum: pkg=httpd state=latest

- name: Enable httpd on system reboot
  service: name=httpd enabled=yes

- name: Check if httpd is running
  command: /usr/bin/systemctl is-active httpd
  ignore_errors: yes
  register: result

- name: Start httpd if httpd is not running
  ansible.builtin.debug:
    var: result
  service:
    name: httpd
    state: started
  when: result.rc != 0

- name: Creating an index.html
  lineinfile:
    path: "{{ dest_folder }}/index.html"
    line: Welcome to my web server
    owner: apache
    group: apache
    create: yes

- name: Enable FirewallD on system reboot
  service: name=firewalld enabled=yes
  notify: restart firewalld

- name: FirewallD enable http/https
  firewalld:
    zone: public
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp
  notify: firewalld reload