---
# tasks file for deploy_vsftpd

- name: Install vsftpd
  yum: pkg=vsftpd state=present

- name: Install Python-Utils
  yum: pkg=policycoreutils-python-utils state=present

- name: Use template to copy FTP config
  template:
    src: vsftpd.j2
    dest: "{{ conf_folder }}/vsftpd.conf"

- name: Create upload directory if it does not exist
  file:
    path: "{{ upload_folder }}"
    state: directory
    mode: '777'
  notify: sec_cont

- name: Enable vsftpd on system reboot
  service: name=vsftpd enabled=yes state=started

- name: Enable FirewallD on system reboot
  service: name=firewalld enabled=yes
  notify: restart firewalld

- name: FirewallD enable access to vsftpd
  firewalld:
    zone: public
    service: "{{ fw_service }}"
    permanent: true
    state: enabled
  notify: firewalld reload

- name: Set ftpd_anon_write flag on and keep it persistent across reboots
  seboolean:
    name: ftpd_anon_write
    state: on
    persistent: yes

- name: test
  shell:
    cmd: ls -Z "{{ upload_folder }}"
  register: test

- name: debug test
  debug:
    var: test