---
# tasks file for deploy_vsftpd

- name: Install vsftpd
  yum: pkg=vsftpd state=present

- name: Use template to copy FTP config
  template:
    src: vsftpd.j2
    dest: "{{ conf_folder }}/vsftpd.conf"

- name: Enable vsftpd on system reboot
  service: name=vsftpd enabled=yes state=started

- name: Enable FirewallD on system reboot
  service: name=firewalld enabled=yes
  notify: restart firewalld

- name: FirewallD enable access to vsftpd
  firewalld:
    zone: public
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - "{{ ftp_listen_port }}/tcp"
    - "{{ ftp_data_port }}/tcp"
    - "{{ pasv_min_port }}-{{ pasv_max_port }}/tcp"
  notify: firewalld reload